from pathlib import Path

path = Path('src/server/scripts/Spells/spell_mastery.cpp')
text = path.read_text()

old_critical = '''    class spell_mastery_critical_block : public AuraScript\n    {\n        PrepareAuraScript(spell_mastery_critical_block);\n\n        void CalculateAmount(AuraEffect const*, int32& amount, bool&)\n        {\n            if (Player* player = GetCaster() ? GetCaster()->ToPlayer() : nullptr)\n                if (Acore::Mastery::HasMasterySpecialization(player, Acore::Mastery::WARRIOR_PROTECTION))\n                    amount = int32(Acore::Mastery::GetMastery(player) * 1.50f);\n        }\n\n        void Register() override\n        {\n            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mastery_critical_block::CalculateAmount, EFFECT_1, SPELL_AURA_MOD_BLOCK_CRIT_CHANCE);\n            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mastery_critical_block::CalculateAmount, EFFECT_2, SPELL_AURA_MOD_BLOCK_PERCENT);\n        }\n    };\n'''
new_critical = '''    class spell_mastery_critical_block : public AuraScript\n    {\n        PrepareAuraScript(spell_mastery_critical_block);\n\n        void CalculateCriticalBlock(AuraEffect const*, int32& amount, bool&)\n        {\n            if (Player* player = GetCaster() ? GetCaster()->ToPlayer() : nullptr)\n                if (Acore::Mastery::HasMasterySpecialization(player, Acore::Mastery::WARRIOR_PROTECTION))\n                    amount = int32(Acore::Mastery::GetMastery(player) * 2.20f);\n        }\n\n        void CalculateBlock(AuraEffect const*, int32& amount, bool&)\n        {\n            if (Player* player = GetCaster() ? GetCaster()->ToPlayer() : nullptr)\n                if (Acore::Mastery::HasMasterySpecialization(player, Acore::Mastery::WARRIOR_PROTECTION))\n                    amount = int32(Acore::Mastery::GetMastery(player) * 0.50f);\n        }\n\n        void Register() override\n        {\n            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mastery_critical_block::CalculateCriticalBlock, EFFECT_1, SPELL_AURA_MOD_BLOCK_CRIT_CHANCE);\n            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mastery_critical_block::CalculateBlock, EFFECT_2, SPELL_AURA_MOD_BLOCK_PERCENT);\n        }\n    };\n'''
if old_critical not in text:
    raise SystemExit('critical block class anchor not found')
text = text.replace(old_critical, new_critical, 1)

old_divine = '''    class spell_mastery_divine_bulwark : public AuraScript\n    {\n        PrepareAuraScript(spell_mastery_divine_bulwark);\n\n        void CalculateAmount(AuraEffect const*, int32& amount, bool&)\n        {\n            if (Player* player = GetCaster() ? GetCaster()->ToPlayer() : nullptr)\n                if (Acore::Mastery::HasMasterySpecialization(player, Acore::Mastery::PALADIN_PROTECTION))\n                    amount = int32(Acore::Mastery::GetMastery(player));\n        }\n\n        void Register() override\n        {\n            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mastery_divine_bulwark::CalculateAmount, EFFECT_0, SPELL_AURA_ADD_FLAT_MODIFIER);\n            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mastery_divine_bulwark::CalculateAmount, EFFECT_1, SPELL_AURA_MOD_BLOCK_PERCENT);\n        }\n    };\n'''
new_divine = '''    class spell_mastery_divine_bulwark : public AuraScript\n    {\n        PrepareAuraScript(spell_mastery_divine_bulwark);\n\n        void CalculateBlock(AuraEffect const*, int32& amount, bool&)\n        {\n            if (Player* player = GetCaster() ? GetCaster()->ToPlayer() : nullptr)\n                if (Acore::Mastery::HasMasterySpecialization(player, Acore::Mastery::PALADIN_PROTECTION))\n                    amount = int32(Acore::Mastery::GetMastery(player));\n        }\n\n        void Register() override\n        {\n            // The converted effect 0 lost its original fourth-effect target and\n            // is intentionally not used. Shield of the Righteous and Bastion of\n            // Glory are handled on their own auras in spell_mastery_tank.cpp.\n            DoEffectCalcAmount += AuraEffectCalcAmountFn(spell_mastery_divine_bulwark::CalculateBlock, EFFECT_1, SPELL_AURA_MOD_BLOCK_PERCENT);\n        }\n    };\n'''
if old_divine not in text:
    raise SystemExit('divine bulwark class anchor not found')
text = text.replace(old_divine, new_divine, 1)

path.write_text(text)
